version: '2.2'
services:
  elasticsearch:
    build:
      context: /etc/elasticsearch
      dockerfile: Dockerfile
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    restart: always
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /vol/es:/usr/share/elasticsearch/data
      - /etc/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    environment:
      SERVER_NAME: kibana.quoting.com
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
    - 5601:5601
    networks:
    - esnet
networks:
  esnet:
    driver: bridge