version: '2.2'
services:
  elasticsearch:
    build:
      context: /etc/elasticsearch
      dockerfile: Dockerfile
    environment:
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms8g -Xmx8g
    restart: always
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /vol/es:/usr/share/elasticsearch/data
      - /etc/elasticsearch/jvm.options:/usr/share/elasticsearch/config/jvm.options
      - /etc/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
networks:
  esnet:
    driver: bridge